# Generated by Django 6.0.7 on 2026-08-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='articles/'),
        ),
    ]
